#!/bin/bash -l

#$ -P ec523bn
#$ -j y
#$ -N YOLOv5
#$ -o logs/yolo-log.qlog

#$ -l h_rt=48:00:00
#$ -pe omp 4

#$ -l gpus=1
#$ -l gpu_c=8.0

module load python3
source .venv/bin/activate

# train
python train.py --img 640 --batch 16 --epochs 50 --data coco.yaml --cfg models/yolov5m-convnext.yaml --weights '' --cache disk --name convnext-yolov5m

# test
python val.py --weights yolov5m.pt --data coco.yaml --img 640 --name convnext-yolov5m